# Created by: Team india
    # Martin Edwin Schjødt Nielsen
    # Jacob Varring
# Build: docker build -f Dockerfile_SourceCode -t martinjakobmsdo/skycaveplayerservice_source_code .
# docker push martinjakobmsdo/skycaveplayerservice_source_code (with default tag "latest")
# Execute with fakeplayerStorage as configuration file: docker run -p 80:80 martinjakobmsdo/skycaveplayerservice_source_code
# Excute  with specific configurataion file: docker run -p 80:80 martinjakobmsdo/skycaveplayerservice_source_code dotnet SkycavePlayerService.api.dll Configuration:File=<configuration filename>.json

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

EXPOSE 80
#Copy source code
COPY SkycavePlayerService.api/ SkycavePlayerService.api/
COPY SkycavePlayerService.Implementations.Repositories/ SkycavePlayerService.Implementations.Repositories/
COPY SkycavePlayerService.Exceptions/ SkycavePlayerService.Exceptions/
COPY SkycavePlayerService.Shared.Contracts/ SkycavePlayerService.Shared.Contracts/
COPY SkycavePlayerService.Shared.Models/ SkycavePlayerService.Shared.Models/
COPY SkycavePlayerService.Implementations.TestDoubles/ SkycavePlayerService.Implementations.TestDoubles/
COPY SkycavePlayerService.Implementations.Storage/ SkycavePlayerService.Implementations.Storage/
COPY SkycavePlayerService.Tests.UnitTests/ SkycavePlayerService.Tests.UnitTests/
COPY SkycavePlayerService.Tests.TestUtilities/ SkycavePlayerService.Tests.TestUtilities/
COPY SkycavePlayerService.Tests.IntegrationTests/ SkycavePlayerService.Tests.IntegrationTests/
#Copy util
COPY /Dockerfile .
COPY Dockerfile_SourceCode .
COPY README.md .
COPY SkycavePlayerService.sln .


RUN dotnet restore "SkycavePlayerService.api/SkycavePlayerService.api.csproj"

WORKDIR "/src/SkycavePlayerService.api"
RUN dotnet build "SkycavePlayerService.api.csproj" -c Release -o /app/build

RUN dotnet publish "SkycavePlayerService.api.csproj" -c Release -o /app/publish

WORKDIR /app/publish

ENV ASPNETCORE_URLS "http://0.0.0.0:80"
CMD ["dotnet", "SkycavePlayerService.api.dll", "Configuration:File=FakePlayerStorage.json"]
